server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  #spring:
  cloud:
    nacos:
      discovery:
#        namespace: dev-12
        server-addr: 192.168.40.128:8848 # nacos服务地址
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5tANPs1DWQ3jLcyryy1r
    keySecret: g7vYabokJCafrubmWRqvl38mAn9Rtv
    bucketName: srb-file-12-27
